package com.rawmakyamu.util.mapping;
// Generated Feb 5, 2018 9:13:34 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMER")
public class Customer implements java.io.Serializable {

    private BigDecimal id;
    private Status status;
    private String firstname;
    private String lastname;
    private String nic;
    private String mobile;
    private String email;
    private Date createdtime;
    private Blob img;
    private Date lastupdatedtime;
    private Set<Trip> trips = new HashSet<Trip>(0);

    public Customer() {
    }

    public Customer(BigDecimal id) {
        this.id = id;
    }

    public Customer(BigDecimal id, Status status, String firstname, String lastname, String nic, String mobile, String email, Date createdtime, Blob img, Date lastupdatedtime, Set<Trip> trips) {
        this.id = id;
        this.status = status;
        this.firstname = firstname;
        this.lastname = lastname;
        this.nic = nic;
        this.mobile = mobile;
        this.email = email;
        this.createdtime = createdtime;
        this.img = img;
        this.lastupdatedtime = lastupdatedtime;
        this.trips = trips;
    }

    @Id
    @SequenceGenerator(name = "SequenceIdGenerator", sequenceName = "CUSTOMER_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SequenceIdGenerator")

    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @Column(name = "FIRSTNAME", length = 64)
    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @Column(name = "LASTNAME", length = 64)
    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Column(name = "NIC", length = 16)
    public String getNic() {
        return this.nic;
    }

    public void setNic(String nic) {
        this.nic = nic;
    }

    @Column(name = "MOBILE", length = 20)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name = "EMAIL", length = 128)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @Column(name = "IMG")
    public Blob getImg() {
        return this.img;
    }

    public void setImg(Blob img) {
        this.img = img;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
    public Set<Trip> getTrips() {
        return this.trips;
    }

    public void setTrips(Set<Trip> trips) {
        this.trips = trips;
    }
}
