package com.rawmakyamu.util.mapping;
// Generated Feb 5, 2018 11:14:40 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Trip generated by hbm2java
 */
@Entity
@Table(name = "TRIP")
public class Trip implements java.io.Serializable {

    private BigDecimal id;
    private Status status;
    private VehicleType vehicleType;
    private Customer customer;
    private Driver driver;
    private String source;
    private String destination;
    private Date startedtime;
    private Date endtime;
    private BigDecimal fare;
    private Date createdtime;
    private Date lastupdatedtime;

    public Trip() {
    }

    public Trip(BigDecimal id) {
        this.id = id;
    }

    public Trip(BigDecimal id, Status status, VehicleType vehicleType, Customer customer, Driver driver, String source, String destination, Date startedtime, Date endtime, BigDecimal fare, Date createdtime, Date lastupdatedtime) {
        this.id = id;
        this.status = status;
        this.vehicleType = vehicleType;
        this.customer = customer;
        this.driver = driver;
        this.source = source;
        this.destination = destination;
        this.startedtime = startedtime;
        this.endtime = endtime;
        this.fare = fare;
        this.createdtime = createdtime;
        this.lastupdatedtime = lastupdatedtime;
    }

    @Id

    @SequenceGenerator(name = "SequenceIdGenerator", sequenceName = "TRIP_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SequenceIdGenerator")
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "VEHICLE")
    public VehicleType getVehicleType() {
        return this.vehicleType;
    }

    public void setVehicleType(VehicleType vehicleType) {
        this.vehicleType = vehicleType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CUSTOMER")
    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DRIVER")
    public Driver getDriver() {
        return this.driver;
    }

    public void setDriver(Driver driver) {
        this.driver = driver;
    }

    @Column(name = "SOURCE")
    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    @Column(name = "DESTINATION")
    public String getDestination() {
        return this.destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "STARTEDTIME", length = 7)
    public Date getStartedtime() {
        return this.startedtime;
    }

    public void setStartedtime(Date startedtime) {
        this.startedtime = startedtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ENDTIME", length = 7)
    public Date getEndtime() {
        return this.endtime;
    }

    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    @Column(name = "FARE", precision = 8)
    public BigDecimal getFare() {
        return this.fare;
    }

    public void setFare(BigDecimal fare) {
        this.fare = fare;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

}
