package com.rawmakyamu.util.mapping;
// Generated Feb 5, 2018 10:31:34 AM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VehicleType generated by hbm2java
 */
@Entity
@Table(name = "VEHICLE_TYPE"
)
public class VehicleType implements java.io.Serializable {

    private BigDecimal id;
    private Status status;
    private String description;
    private BigDecimal priceKm;
    private BigDecimal priceMin;
    private BigDecimal baseFare;
    private BigDecimal commission;
    private Byte personCapacity;
    private Date createdtime;
    private Date lastupdatedtime;
    private String lastupdateduser;
    private Set<Trip> trips = new HashSet<Trip>(0);

    public VehicleType() {
    }

    public VehicleType(BigDecimal id) {
        this.id = id;
    }

    public VehicleType(BigDecimal id, Status status, String description, BigDecimal priceKm, BigDecimal priceMin, BigDecimal baseFare, BigDecimal commission, Byte personCapacity, Date createdtime, Date lastupdatedtime, String lastupdateduser, Set<Trip> trips) {
        this.id = id;
        this.status = status;
        this.description = description;
        this.priceKm = priceKm;
        this.priceMin = priceMin;
        this.baseFare = baseFare;
        this.commission = commission;
        this.personCapacity = personCapacity;
        this.createdtime = createdtime;
        this.lastupdatedtime = lastupdatedtime;
        this.lastupdateduser = lastupdateduser;
        this.trips = trips;
    }

    @Id
    @SequenceGenerator(name = "SequenceIdGenerator", sequenceName = "VEHICLE_TYPE_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SequenceIdGenerator")

    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @Column(name = "DESCRIPTION", length = 64)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "PRICE_KM", precision = 6)
    public BigDecimal getPriceKm() {
        return this.priceKm;
    }

    public void setPriceKm(BigDecimal priceKm) {
        this.priceKm = priceKm;
    }

    @Column(name = "PRICE_MIN", precision = 6)
    public BigDecimal getPriceMin() {
        return this.priceMin;
    }

    public void setPriceMin(BigDecimal priceMin) {
        this.priceMin = priceMin;
    }

    @Column(name = "BASE_FARE", precision = 6)
    public BigDecimal getBaseFare() {
        return this.baseFare;
    }

    public void setBaseFare(BigDecimal baseFare) {
        this.baseFare = baseFare;
    }

    @Column(name = "COMMISSION", precision = 4)
    public BigDecimal getCommission() {
        return this.commission;
    }

    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    @Column(name = "PERSON_CAPACITY", precision = 2, scale = 0)
    public Byte getPersonCapacity() {
        return this.personCapacity;
    }

    public void setPersonCapacity(Byte personCapacity) {
        this.personCapacity = personCapacity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicleType")
    public Set<Trip> getTrips() {
        return this.trips;
    }

    public void setTrips(Set<Trip> trips) {
        this.trips = trips;
    }
}
